### ISSUE TITLE
OpenShift Template Install Broken

### ISSUE THREAD

**Issue by InfoSec812** [jfrog/artifactory-docker-examples#103]
1. The `install.sh` script has `/bin/sh` for the shebang, but the syntax requires `/bin/bash`.
2. You should use the [PostgreSQL template](https://github.com/openshift/origin/blob/master/examples/db-templates/postgresql-persistent-template.json) included with OpenShift which runs without root privileges -

**Comment by elioengcomp** [comment]
Hi @InfoSec812 ,

Thanks for opening this case.

I have fixed the shell comments as you pointed out.

The PostgreSQL templates provided in this repository are a reference to the database deployment step and its usage is completely optional. If you have a supported database available to be used by Artifactory, you can ignore them.

Best.
Elio

**Comment by jfrog-aparicio** [comment]
Closing as this integration has been deprecated.
