### ISSUE TITLE
Can not install self signed CA certificates starting with 6.2.0

### ISSUE THREAD

**Issue by andriypotapov** [jfrog/artifactory-docker-examples#108]
**Use case**
Have to use self signed CA in order for Artifactory to connect to internet.
This is pretty standard setup for people in "enterprise" setting since I did not find any specific parameter or procedure to address self signed CA I wonder what would be the best way to handle this.

**Docker changes**
Effectively updated Artifactory Dockerfile with following commands
```
FROM docker.bintray.io/jfrog/artifactory-oss:6.3.0
...
COPY ./ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates --fresh
```
**Problem**
Was working fine with 6.1.0 but fails starting with 6.2.0 
```
Clearing symlinks in /etc/ssl/certs...
rm: cannot remove './Comodo_AAA_Services_root.pem': Permission denied
```
**Notes**
Probably have same explanation as for #104

**Comment by andriypotapov** [comment]
**Workaround**
1. Commented out ca-update in Dockerfile
```
FROM docker.bintray.io/jfrog/artifactory-oss:6.3.0
...
COPY ./ca-certificates/* /usr/local/share/ca-certificates/
#RUN update-ca-certificates --fresh
```
2. Build and start container
3. open shell in container as root
`sudo docker exec -u root -t -i container_id /bin/bash`
4. Manually update container 
`update-ca-certificates --fresh`

**Comment by andriypotapov** [comment]
Having this in documentation or Q&A would have solved my problem.
```
FROM docker.bintray.io/jfrog/artifactory-oss:6.3.0
...
# switch to root
USER root
COPY ./ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates --fresh

# switch back to custom user
USER sonar
...
```

**Comment by shahiinn** [comment]
@andriypotapov : The solution is to import the certificate to java keystore as you mentioned. 
However, we would like to inform you you that from Artifactory version 7x, you can add the certificate under $JFROG_HOME/<product>/var/etc/security/keys/trusted which will automatically be updating the keystore on Artifcatory start/restart. Please find more details [here](https://www.jfrog.com/confluence/display/JFROG/Managing+TLS+Certificates)

**Comment by JfrogPrasanna** [comment]
With a recommendation to move to  the latest version of compose, we are closing this issue as this repo is deprecated, and this issue is fixed  in the latest compose files in 7.x.
