### ISSUE TITLE
artifactory-oss.yml not working correctly

### ISSUE THREAD

**Issue by ghost** [jfrog/artifactory-docker-examples#113]
Hi,
I try deploy artifactory-oss.yml but I still get error 

`ERROR: Max number of open files 1024, is too low. Cannot run Artifactory!`

When I start it with docker run --ulimit nofile="32000:32000" its ok, but I need this run in docker stack because I use swarm and I want use ingress network, cloud you help me?

Docker version 18.03.1-ce

Docker info:

```
Containers: 10
 Running: 4
 Paused: 0
 Stopped: 6
Images: 22
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: gcu8onuqg3836c1imxuf6dbdd
 Is Manager: true
 ClusterID: ivlgf7yabudu9703bbahoxujk
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.2.248
 Manager Addresses:
  10.0.2.248:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.62-70.117.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.853GiB
Name: ip-10-0-2-248.ec2.internal
ID: RW3Z:WBFQ:DUU5:E54D:4IJP:SEME:ZLE4:A6VS:H3BJ:7BD4:2GEJ:PSSA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: simbiphp
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by Ricky-N** [comment]
+1, I cannot get Artifactory to run in Docker Swarm due to the default 1024 file descriptor default limit. The `ulimit` settings don't actually work for swarm mode, and I cannot find a workaround for modifying this requirement at the Artifactory container level. I'm hesitant to start modifying global ulimit so I'll likely just drop using Artifactory altogether in favor of hosting individual repository types for the short term.

**Comment by eldada** [comment]
There is a workaround in the Artifactory entrypoint.
You can pass an override value to the environment variable `MIN_MAX_OPEN_FILES` (defaults to 10000).
```
   environment:
     - MIN_MAX_OPEN_FILES=1000
```
Artifactory really needs these limits to function properly, so take care when overriding these values.

Let us know if it helped you.

**Comment by ori10DevOps** [comment]
Thanks! it's working!
