### ISSUE TITLE
Structure in docker to upload upload projects

### ISSUE THREAD

**Issue by bastyy** [jfrog/artifactory-docker-examples#119]
Hello, a doubt, I have this structure in my docker volumes: data/artifactory/ and within artifactory I have: access backup data etc logs replicator, however where do I leave the repo that I want to load?

Greetings and thanks!

**Comment by eldada** [comment]
@bastyy - what do you mean:
> ... where do I leave the repo that I want to load?
What repo? Load where? Can you link to related documentation?
