### ISSUE TITLE
Add feature to add and persist Nginx directive to auto-updated Nginx configuration

### ISSUE THREAD

**Issue by michaelhuettermann** [jfrog/artifactory-docker-examples#128]
see https://www.jfrog.com/jira/browse/RTFACT-16743

**Comment by michaelhuettermann** [comment]
Without this feature (or maybe it is a bug fix?), and without you implementing RTFACT-16743, using your Docker Compose based approach is not possible in practice, respectively does not make much sense  (e.g.: auto-updating disabled *and* using the port method for Docker (still pretty spread these days) lead to a maintenance nightmare)

**Comment by JfrogPrasanna** [comment]
I see that the issue in question is resolved. Going ahead and  closing this as this repo is under deprecation.
