### ISSUE TITLE
Scary outdated java

### ISSUE THREAD

**Issue by TJM** [jfrog/artifactory-docker-examples#129]
The java version in the artifactory-pro:latest (6.5.2 at this point) image is still OpenJDK 8 u131, from like 18 months ago. Please update the "FROM" line on Dockerfile.artifactory (actually all of them) to a more recent version.

~tommy

PS: I appreciate that the Dockerfile is embedded within the image, but it would be good if it were in a public facing repo (perhaps this one) so that we could submit PR's for updates.

**Comment by TJM** [comment]
Example: https://github.com/TJM/artifactory-docker-examples/blob/standalone/standalone/Dockerfile

Also, for giggles, check out the Alpine Linux based Dockerfile:
https://github.com/TJM/artifactory-docker-examples/blob/standalone/standalone/Dockerfile.alpine

**Comment by eldada** [comment]
@TJM - thanks for the feedback and examples. As you noted, the base versions are old and we are working on a more recent version. Also the Alpine is a great idea (already discussed internally), but there are customers not willing to use it, so we use a more accepted base. I hope we'll have more to share in the following weeks.

**Comment by TJM** [comment]
@eldada Thanks for the response! We can't use the currently published version due to all the security vulnerabilities in it. Please do update the base (FROM), and preferably, don't "COPY" zip files into the image. It would be best to convert them to .tar.gz and use "ADD" or just expand them and COPY the contents in. It *appears* that this is being built from the "source" dir (since its just standalone.zip), so instead of grabbing that archive, just copy the contents of the "build" directory (or whatever) that the archive was created from.

RE: Alpine -  I would recommend publishing both versions, similar to how the openjdk images are produced. 

Honestly, I would personally rather use Enterprise Linux (CentOS) than Debian, but I think we are supposed to not really care what is in the image, right? :-/

Given the opportunity to decrease the size of the image by ~1GB, I would think people would be willing to give alpine a try. It's not like you need the other GB of "tools" installed on the base OS, right?

Are the maintainers  of the artifactory docker image looking at these repos, or should we email them directly (or submit a support ticket?)

~tommy

**Comment by eldada** [comment]
Hey Tommy. We are already working on the new Java version. Should be in one of the coming releases.
All your comments are valid and make good sense. If there's a particular one you think should be pushed, go ahead and open a [JIRA](https://www.jfrog.com/jira/secure/Dashboard.jspa) ticket and our teams will evaluate it. You can also get some voters and help push a specific change you feel is important.

RE: Adding an Alpine distribution. We are evaluating this as well.
RE: Base OS. We use the official openjdk image, which by default is based on Debian.
RE: Size. I strongly agree, but as mentioned before, this is not a strong requirement.

**Comment by eldada** [comment]
I'm happy to update that Artifactory 6.9.0 now comes with Java 11 based on the [distroless](https://github.com/GoogleContainerTools/distroless) base image.
This also dramatically reduced the size of the image.

**Comment by TJM** [comment]
@eldada - Thanks for your efforts, but it does not appear to be in 6.9.0.

```
$ docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS               NAMES
e544c5f71e01        docker.bintray.io/jfrog/artifactory-pro:6.9.0   "/entrypoint-artifac…"   55 seconds ago      Up 52 seconds       8081/tcp            ecstatic_volhard
$ docker exec -it e544c5f71e01 bash
artifactory@e544c5f71e01:/$ cat /docker/artifactory-pro/Dockerfile.artifactory
FROM docker.bintray.io/jfrog/openjdk:8u181

LABEL maintainer devops@jfrog.com
```

**Comment by eldada** [comment]
Oooppssss.... I messed it up with an internal version, which will be released soon. sorry for the confusion.

**Comment by eldada** [comment]
Now we have it... Artifactory 6.9.1 has a new base image and Java 11.
