### ISSUE TITLE
Compatibility of Xray on Openshift platform

### ISSUE THREAD

**Issue by sanjeevkarani** [jfrog/artifactory-docker-examples#138]
Missing documentation on Supported Openshift platform versions for Xray installation
Tested: Xray v2.5.1 installs on Openshift platform v3.9.x
               Xray v2.6.0 throws error on Openshift platform v3.9.x

**Comment by eldada** [comment]
@jainishshah17 , @elioengcomp - guys can you take a look?
- Missing docs
- Why Xray 2.6.0 fails on OS 3.9.x

**Comment by sanjeevkarani** [comment]
Updates: Xray v2.6.3 installs on Openshift platform v3.10.83

**Comment by jainishshah17** [comment]
@eldada It requires to update OS templates as our installer has evolved.

**Comment by jfrog-aparicio** [comment]
This integration is deprecated.
