### ISSUE TITLE
Postgres upgrade?

### ISSUE THREAD

**Issue by tjohnston-cd** [jfrog/artifactory-docker-examples#142]
I just upgraded from an Artifactory Pro 6.5.x version to 6.7.3 using [this compose file](https://github.com/jfrog/artifactory-docker-examples/blob/master/docker-compose/artifactory/artifactory-pro.yml).

`artifactory` and `nginx` came up correctly, but `postgresql` did not. `docker logs postgresql` showed **"The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.11."**

I see the postgres version was changed in [this commit](https://github.com/jfrog/artifactory-docker-examples/commit/a748c1c921f728bd88d1d0c4eb544828a2cd9208)

Do I need to upgrade my postgres DB? What is the best practice when using this repo to deploy artifactory?

**Comment by eldada** [comment]
Hi @tjohnston-cd . This repository is meant to provide examples for setting up Artifactory and Xray in various Docker based scenarios.
PostgreSQL upgrade is not required. We just aligned to a new (recommended) baseline of version 9.6.11. The older version will still work as expected.
If you wish to use the newer PostgreSQL version, you will need to perform a DB export from 9.5 -> import to 9.6.

**Comment by PtyMatt** [comment]
@tjohnston-cd (and everybody else stucked by a Docker Postgresql upgrade), you should read [that discussion](https://github.com/docker-library/postgres/issues/37) from the official image repo.
