### ISSUE TITLE
[ERROR] (o.a.w.s.ArtifactoryFilter:194) - Artifactory failed to initialize: Context is null

### ISSUE THREAD

**Issue by marcuschaney** [jfrog/artifactory-docker-examples#146]
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}

After attempting to configure the binarystore.xml to utilize my S3 bucket: Config below:

<chain template="s3">
<provider id="s3" type="s3">
<endpoint>http://s3-us-gov-west-1.amazonaws.com</endpoint>
<region>us-gov-west-1</region>
<roleName>XXX-EC2Role</roleName>
<path>artifactory</path>
<bucketName>XXXXXX</bucketName>
<httpsOnly>false</httpsOnly>
<refreshCredentials>true</refreshCredentials>
</provider>
</chain>

More infro from the logs:
2019-02-20 00:56:21,225 [art-init] [INFO ] (o.j.s.b.p.t.BinaryProviderClassScanner:76) - Added 'blob' from jar:file:/opt/jfrog/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/artifactory-storage-db-6.7.3.jar!/
2019-02-20 00:56:21,248 [art-init] [INFO ] (o.j.s.b.p.t.BinaryProviderClassScanner:76) - Added 'empty, external-file, external-wrapper, file-system, cache-fs, retry' from jar:file:/opt/jfrog/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/binary-store-core-3.1.40.jar!/
2019-02-20 00:56:22,034 [art-init] [WARN ] (o.a.s.ArtifactoryApplicationContext:243) - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'xrayAddonImpl' defined in URL [jar:file:/opt/jfrog/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/artifactory-addon-xray-6.7.3.jar!/org/artifactory/addon/xray/XrayAddonImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.artifactory.api.config.CentralConfigService]:

**Comment by marcuschaney** [comment]
As soon as I changed the binarystore.xml file back to :+1: 
<config version="1">
    <chain template="file-system"/>
</config>

Artifactory came up just fine. Thus, I know I must be doing something wrong with my config.

**Comment by marcuschaney** [comment]
Trying to make this happen:

https://www.jfrog.com/confluence/display/RTF/S3+Object+Storage#S3ObjectStorage-AutomaticFilestoreMigration(Recommended)

**Comment by marcuschaney** [comment]
Resolved.

**Comment by johnny445** [comment]
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}

**Comment by johnny445** [comment]
I'm getting this error anyone please tell me how to solve this

**Comment by asinvrer** [comment]
Nice nice

**Comment by asinvrer** [comment]
Nice Nice

**Comment by johnny445** [comment]
![artifact](https://user-images.githubusercontent.com/45600458/60382558-47a60780-9a82-11e9-970f-84bc054536d8.jpg)
I'm facing this error anyone please tell me what mistake I have done?

**Comment by eldada** [comment]
@johnny445 - can you provide steps to reproduce? Also - I suggest opening this in a new issue to get better traction.
