### ISSUE TITLE
Please provide a master key file manually in '/opt/jfrog/artifactory/etc/security/master.key'.

### ISSUE THREAD

**Issue by marcuschaney** [jfrog/artifactory-docker-examples#147]
I'm running Artifactory via docker-compose and attempting to link to an external Postgres database. I continue to encounter "master key" related issues when trying to run Artifactory. 

"- Found existing master key fingerprint in the DB, without master.key file. Please provide a master key file manually in '/opt/jfrog/artifactory/etc/security/master.key'."

As anyone ever experienced this?

**Comment by marcuschaney** [comment]
[JFrog-Access] [WARN ] (o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext:550) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jerseyConfig' defined in URL [jar:file:/opt/jfrog/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-4.1.44.jar!/org/jfrog/access/rest/config/JerseyConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jfrog.access.rest.config.JerseyConfig]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter' defined in URL [jar:file:/opt/jfrog/artifactory/tomcat/webapps/access/WEB-INF/lib/access-server-rest-4.1.44.jar!/org/jfrog/access/server/rest/filter/AuthFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationServiceImpl': Unsatisfied dependency expressed through method 'setCertificateService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accessStartupService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Master key mismatch. The provided master.key file does't match the DB fingerprint. Make sure your db.properties configurations are valid and the master key matches the DB you are trying to connect to.
artifactory    | 2019-03-19 20:42:36,436 [localhost-startStop-2] [JFrog-Access] [ERROR] (o.s.b.SpringApplication:771) - Application startup failed

Latest error after I manually created the master.key file and provided the AWS KMS key..

**Comment by eldada** [comment]
@marcuschaney - it looks like you have connected to an existing DB (that was already setup by Artifactory) with a new Artifactory deployment (or did not persist file system from a previous deployment).
When Artifactory starts, if master key is not in the DB, it will use existing key or create a new one and then register it in DB and any future connections will use this key for validation (comparing file to DB).
You should setup a new Artifactory with a clean DB in this case.

**Comment by marcuschaney** [comment]
@eldada Thank you for your reply! After replacing my previous RDS Postgres instance, I attempted to run a new container, and now I'm receiving the below error:

artifactory    | Mar 20, 2019 2:57:47 PM org.apache.catalina.core.StandardContext startInternal
artifactory    | SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
artifactory    | Mar 20, 2019 2:57:47 PM org.apache.catalina.core.StandardContext startInternal
artifactory    | SEVERE: Context [/artifactory] startup failed due to previous errors
artifactory    | 14:57:47.438 [localhost-startStop-1] DEBUG org.artifactory.webapp.servlet.ArtifactoryContextConfigListener - Context shutdown started
artifactory    | 14:57:47.438 [localhost-startStop-1] DEBUG org.artifactory.webapp.servlet.ArtifactoryContextConfigListener - Context shutdown Finished
artifactory    | Mar 20, 2019 2:57:47 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
artifactory    | WARNING: The web application [artifactory] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory lea                                                           k. Stack trace of thread:
artifactory    |  sun.nio.fs.LinuxWatchService.poll(Native Method)
artifactory    |  sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
artifactory    |  sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
artifactory    |  java.lang.Thread.run(Thread.java:748)

Any ideas?

V/r
Marcus

**Comment by marcuschaney** [comment]
@eldada If I'm doing an external database, where do I map the port? Just under "artifactory"? Copy of my docker compose file is below:

version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.7.3
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /data/artifactory/artifactory_extra_conf:/artifactory_extra_conf
    environment:
     - DB_TYPE=postgresql
     - DB_USER=artifactory
     - DB_PASSWORD=xxxxxxxxx
     - DB_HOST=xxxxxxxxxxxxxxxx.us-gov-west-1.rds.amazonaws.com
     - DB_PORT=5432
     # https://github.com/docker/compose/issues/4485
     #You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign.
     #This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

**Comment by marcuschaney** [comment]
type=postgresql
driver=org.postgresql.Driver
url=jdbc:postgresql://xxxxxxxxxxxxxxxxxs-gov-west-1.rds.amazonaws.com:5432/artifactory
username=artifactory
password=fxxxxxxxxx

Is the above syntax correct for the db.properties file?

**Comment by marcuschaney** [comment]
More:

artifactory    | 2019-03-20 18:06:41.576  INFO 303 --- [ost-startStop-2] o.j.a.s.startup.AccessHomeFinderImpl     : Using JFrog Access home at '/opt/jfrog/artifactory/access' resolved from: System property (Artifactory)
artifactory    | 2019-03-20 18:06:42.006  INFO 303 --- [ost-startStop-2] o.j.a.migration.ConfigMigrationRunner    : Current version of Access Home is 3, latest version is 4. Applying migrations.
artifactory    | 2019-03-20 18:06:42.011  INFO 303 --- [ost-startStop-2] o.j.a.migration.ConfigMigrationRunner    : Migrating Access Home to version 4
artifactory    | 2019-03-20 18:06:42,372 [localhost-startStop-2] [JFrog-Access] [INFO ] (o.j.a.c.JFrogApplicationContextInitializer:74) - Using JFrog Access home at '/opt/jfrog/artifactory/access'
artifactory    | 2019-03-20 18:06:42,402 [localhost-startStop-2] [JFrog-Access] [INFO ] (o.j.a.AccessApplication:48) - Starting AccessApplication v4.1.44 on 8105a839f591 with PID 303 (/opt/jfrog/artifactory/tomcat/webapps/access/WEB-INF/lib/access-application-4.1.44.jar started by artifactory in /)
artifactory    | 2019-03-20 18:06:42,402 [localhost-startStop-2] [JFrog-Access] [INFO ] (o.j.a.AccessApplication:597) - The following profiles are active: production,grpc
artifactory    | 2019-03-20 18:06:42 [UNDEFINED] [INFO ] Fetched Artifactory [artifactory.home=null] from servlet context
artifactory    | 2019-03-20 18:06:42 [UNDEFINED] [INFO ] Resolved Artifactory home by logger [artifactory.home=/opt/jfrog/artifactory].
artifactory    | 18:06:42.997 [Thread-7] INFO org.jfrog.config.watch.FileWatchingManager - Starting watch of folder configurations
artifactory    | 18:06:43.045 [localhost-startStop-1] DEBUG org.artifactory.converter.VersionProviderImpl - Last Artifactory database version is: v673
artifactory    | 18:06:43.091 [localhost-startStop-1] INFO org.artifactory.converter.ConvertersManagerImpl - Triggering PRE_INIT conversion, from v673 to v673
artifactory    | 18:06:43.091 [localhost-startStop-1] INFO org.artifactory.converter.ConvertersManagerImpl - Finished PRE_INIT conversion, current version is: v673
artifactory    | 2019-03-20 18:06:43 [ARTIFACTORY] [INFO ] Master key file found.
artifactory    | Mar 20, 2019 6:06:43 PM org.apache.catalina.core.StandardContext startInternal
artifactory    | SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
artifactory    | Mar 20, 2019 6:06:43 PM org.apache.catalina.core.StandardContext startInternal
artifactory    | SEVERE: Context [/artifactory] startup failed due to previous errors
artifactory    | 18:06:43.572 [localhost-startStop-1] DEBUG org.artifactory.webapp.servlet.ArtifactoryContextConfigListener - Context shutdown started
artifactory    | 18:06:43.573 [localhost-startStop-1] DEBUG org.artifactory.webapp.servlet.ArtifactoryContextConfigListener - Context shutdown Finished

**Comment by marcuschaney** [comment]
Accessed the localhost log in the container and this seems to be the root cause (cannot connect to DB)

20-Mar-2019 21:34:07.727 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.artifactory.webapp.servlet.ArtifactoryHomeConfigListener]
 java.lang.RuntimeException: Could't establish connection with db: jdbc:postgresql://artifactorytestdb.cegxppgui6sf.us-gov-west-1.rds.amazonaws.com:5432/artifactory
        at org.jfrog.config.db.TemporaryDBChannel.<init>(TemporaryDBChannel.java:35)
        at org.artifactory.common.ArtifactoryConfigurationAdapter.getDbChannel(ArtifactoryConfigurationAdapter.java:209)
        at org.jfrog.config.wrappers.ConfigurationManagerImpl.getDBChannel(ConfigurationManagerImpl.java:428)
        at org.artifactory.config.MasterKeyBootstrapUtil.dbChannel(MasterKeyBootstrapUtil.java:234)
        at org.artifactory.config.MasterKeyBootstrapUtil.tryToCreateTable(MasterKeyBootstrapUtil.java:115)
        at org.artifactory.config.MasterKeyBootstrapUtil.validateOrInsertKeyInformation(MasterKeyBootstrapUtil.java:85)
        at org.artifactory.config.MasterKeyBootstrapUtil.handleMasterKey(MasterKeyBootstrapUtil.java:66)
        at org.artifactory.webapp.servlet.BasicConfigManagers.initHomes(BasicConfigManagers.java:115)
        at org.artifactory.webapp.servlet.BasicConfigManagers.initialize(BasicConfigManagers.java:101)
        at org.artifactory.webapp.servlet.ArtifactoryHomeConfigListener.contextInitialized(ArtifactoryHomeConfigListener.java:53)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:629)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1839)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: FATAL: database "artifactory" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2586)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:113)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at org.jfrog.config.db.TemporaryDBChannel.<init>(TemporaryDBChannel.java:31)
        ... 22 more

20-Mar-2019 21:34:07.728 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.artifactory.webapp.servlet.logback.LogbackConfigListener]
 java.lang.IllegalStateException: Artifactory home not initialized

**Comment by marcuschaney** [comment]
Progress after changing the database name from /artifactory to /artifactorytestdb (which is what the instance is named in AWS. Now I get the below:

artifactory    | INFO: Starting ProtocolHandler ["ajp-nio-8019"]
artifactory    | 2019-03-20 21:54:10,774 [art-init] [INFO ] (o.a.s.ArtifactoryApplicationContext:503) - Artifactory application context set to NOT READY by refresh
artifactory    | 2019-03-20 21:54:10,775 [art-init] [INFO ] (o.a.s.ArtifactoryApplicationContext:243) - Refreshing artifactory: startup date [Wed Mar 20 21:54:10 UTC 2019]; root of context hierarchy
artifactory    | 2019-03-20 21:55:08,286 [art-init] [ERROR] (o.a.w.s.ArtifactoryContextConfigListener:96) - Application could not be initialized: class path resource [jar:war:file:/opt/jfrog/artifactory/webapps/] cannot be resolved to URL because it does not exist
artifactory    | java.lang.reflect.InvocationTargetException: null
artifactory    |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
artifactory    |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
artifactory    |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
artifactory    |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
artifactory    |        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:211)
artifactory    |        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.access$200(ArtifactoryContextConfigListener.java:67)
artifactory    |        at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:92)
artifactory    | Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Could not resolve bean definition resource pattern [jar:war:file:/opt/jfrog/artifactory/webapps/artifactory.war*/WEB-INF/lib/artifactory-addon-bower-6.7.3.jar!/META-INF/addon.xml]; nested exception is java.io.FileNotFoundException: class path resource [jar:war:file:/opt/jfrog/artifactory/webapps/] cannot be resolved to URL because it does not exist
artifactory    |        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:229)
artifactory    |        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
artifactory    |        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252)
artifactory    |        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
artifactory    |        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
artifactory    |        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
artifactory    |        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:538)
artifactory    |        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:452)
artifactory    |        at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:243)
artifactory    |        at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:143)
artifactory    |        ... 7 common frames omitted
artifactory    | Caused by: java.io.FileNotFoundException: class path resource [jar:war:file:/opt/jfrog/artifactory/webapps/] cannot be resolved to URL because it does not exist
artifactory    |        at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
artifactory    |        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:413)
artifactory    |        at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:287)
artifactory    |        at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1163)
artifactory    |        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:216)
artifactory    |        ... 16 common frames omitted

Dies here now.

**Comment by eldada** [comment]
@marcuschaney - can you contact our support with this? I think that you'll get a better response and help there. support@jfrog.com.
Update this thread with the findings.

**Comment by marcuschaney** [comment]
The lastest issue was due to a size limitation for the /var directory. Resized and was good to go:

lsblk
growpart /dev/xvda 2
pvresize /dev/xvda
lvexted -L +2G /dev/mapper/VolGroup00-varVol
resize2fs /dev/mapper/VolGroup00-varVol

**Comment by eldada** [comment]
Thanks for updating @marcuschaney! Happy it's resolved.
