### ISSUE TITLE
Artifactory 6.9.1: apt-get not found

### ISSUE THREAD

**Issue by fritzdj** [jfrog/artifactory-docker-examples#154]
When using docker.bintray.io/jfrog/artifactory-pro:6.9.1, we are seeing `apt-get not found` errors when attempting to run apt-get cmds. There are some examples using apt-get (https://github.com/jfrog/artifactory-docker-examples/blob/master/dc-os/Docker/HA/Dockerfile) with 6.9.1, but this looks to not be working anymore after 6.9.0.

**Comment by eldada** [comment]
The new Artifactory Docker image (6.9.1) has a new base image, which is not based on Debian (that was coming with the openjdk image).
The new base image is made with the [google distroless](https://github.com/GoogleContainerTools/distroless) framework.
You can find our sources in our [jfrog-distroless repository](https://github.com/jfrog/jfrog-distroless).

**Comment by fritzdj** [comment]
Thanks for the info @eldada. Dockerfiles like https://github.com/jfrog/artifactory-docker-examples/blob/master/dc-os/Docker/HA/Dockerfile will need to be refactored now, correct? This is something we'll need to investigate - please let me know if you have a workaround for that one.

**Comment by eldada** [comment]
@fritzdj - I update the Dockerfiles to use `wget` instead of `curl`. I also removed the `apt-get install` as it seems we don't use its tools anyway.
Are you able to test this?

**Comment by fritzdj** [comment]
@eldada, we have another need to run `apt-get install python-pip -y && pip install awscli`. We are using this to decrypt the encrypted PW for the DB ID at runtime.

**Comment by eldada** [comment]
@fritzdj - Since the new base image for Artifactory is tightened to exclude a lot of common OS packages and libs, you will have to "self bake" this.
I suggest you work with `wget` to download the binaries needed for `python`, `pip` and `awscli`. AFAIK, they can all be downloaded directly as binaries bundles. Once downloaded, you have `tar` and `unzip` to extract.

**Comment by elig** [comment]
@fritzdj - I have added a few examples, hope it will help...

**Comment by eldada** [comment]
Examples can be found in https://github.com/jfrog/jfrog-distroless/tree/master/customize-example
