### ISSUE TITLE
CrashLoopBackoff error when I use my own artifactory image and deployment

### ISSUE THREAD

**Issue by guilhermelac001** [jfrog/artifactory-docker-examples#161]
I've beem trying to configure artifactory-oss so I can set admin password upon creating the container and linking to google binary storage. I'm using k8s so I used kompose to translate between docker-compose and kubernetes deployment. I have my own artifactory image on gcp and that is the one I use while creating the pod. 

The problem that i'm having is that all my container works, but the artifactory. It keeps giving me de crashLoopBackof error.  This is the deployment: 

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  containers:
  - env:
    - name: DB_PASSWORD
      value: password
    - name: DB_TYPE
      value: postgresql
    - name: DB_USER
      value: artifactory
    image: gcr.io/emb-infra/artifactory-teste:latest
    name: artifactory
    ports:
    - containerPort: 8081
    resources: {}
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: artifactory
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  containers:
  - env:
    - name: ART_BASE_URL
      value: http://artifactory:8081/artifactory
    - name: SSL
      value: "true"
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:5.4.4
    name: nginx
    ports:
    - containerPort: 80
    - containerPort: 443
    resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  containers:
  - env:
    - name: POSTGRES_DB
      value: artifactory
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_USER
      value: artifactory
    image: docker.bintray.io/postgres:9.6.11
    name: postgresql
    ports:
    - containerPort: 5432
    resources: {}
  restartPolicy: OnFailure
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgresql
status:
  loadBalancer: {}

----------------------------------------------------------------------
There are no logs generated. The only info I have is the pod describe: 
-----------------------------------------------------------------------

Name:               artifactory
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               gke-kube-phpipam-pool-1-6b696b70-jr2z/10.128.0.4
Start Time:         Fri, 07 Jun 2019 14:16:48 -0300
Labels:             io.kompose.service=artifactory
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"io.kompose.service":"artifactory"},"name"...
                    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container artifactory
Status:             Running
IP:                 10.60.2.70
Containers:
  artifactory:
    Container ID:   docker://36b1fa43367a4e2858b55a84ae705d6e0f52542984784a3a809b52566363565d
    Image:          gcr.io/emb-infra/artifactory-teste:latest
    Image ID:       docker-pullable://gcr.io/emb-infra/artifactory-teste@sha256:40d354b007cc34755c19a5f645c83b1e5c6b38abc2ebceb5eecdea18d4427a30
    Port:           8081/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 07 Jun 2019 14:17:31 -0300
      Finished:     Fri, 07 Jun 2019 14:17:31 -0300
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:  100m
    Environment:
      DB_PASSWORD:  password
      DB_TYPE:      postgresql
      DB_USER:      artifactory
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5dn7s (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-5dn7s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5dn7s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                            Message
  ----     ------     ----               ----                                            -------
  Normal   Scheduled  60s                default-scheduler                               Successfully assigned default/artifactory to gke-kube-phpipam-pool-1-6b696b70-jr2z
  Normal   Pulling    18s (x4 over 60s)  kubelet, gke-kube-phpipam-pool-1-6b696b70-jr2z  pulling image "gcr.io/emb-infra/artifactory-teste:latest"
  Normal   Pulled     18s (x4 over 59s)  kubelet, gke-kube-phpipam-pool-1-6b696b70-jr2z  Successfully pulled image "gcr.io/emb-infra/artifactory-teste:latest"
  Normal   Created    18s (x4 over 59s)  kubelet, gke-kube-phpipam-pool-1-6b696b70-jr2z  Created container
  Normal   Started    17s (x4 over 59s)  kubelet, gke-kube-phpipam-pool-1-6b696b70-jr2z  Started container
  Warning  BackOff    2s (x6 over 57s)   kubelet, gke-kube-phpipam-pool-1-6b696b70-jr2z  Back-off restarting failed container

**Comment by JfrogPrasanna** [comment]
Please move to the latest  helm charts for  Kubernetes [here](https://github.ccom/jfrog/charts) This repo is under deprecation and hence closing this issue.
