### ISSUE TITLE
Xray HA in Docker

### ISSUE THREAD

**Issue by katzefudder** [jfrog/artifactory-docker-examples#164]
With Artifactory HA available [here](https://github.com/jfrog/artifactory-docker-examples/blob/master/docker-compose/artifactory/artifactory-ha.yml), there's no example Docker compose file for running Xray as an HA cluster. Can you please provide an example `xray-ha.yml`?

**Comment by eldada** [comment]
Setting up Xray HA with Docker compose is a bit more complex as you have to setup the RabbitMQ clustering.
We will release a formal Docker compose HA for Xray with the next major release of Xray in a few months.

**Comment by katzefudder** [comment]
I know it's a bite more complex to have a generic docker-compose.yml to rule all use cases, especially when it comes to spin up a cluster.
Please have a look at my PR:
https://github.com/jfrog/artifactory-docker-examples/pull/166

**Comment by asinvrer** [comment]
Stop bitches

**Comment by katzefudder** [comment]
@eldada what do you think about my approach?

**Comment by JfrogPrasanna** [comment]
With the release of 3.0 and support for HA. This will be closed and also this repo is under deprecation.
