### ISSUE TITLE
Upgraded xray docker-stack 2.8.9 to 2.9.0, and now I get "error token exchange" because of "405 Method not allowed"

### ISSUE THREAD

**Issue by SnorreSelmer** [jfrog/artifactory-docker-examples#174]
`[2019/09/11 11:49:34 UTC] [EROR] (jfrog.com/xray/pkg/access/access_sso.(*AccessSsoClient).ExchangeToken:73) Failed to exchange token , err: statusCode: 405,
 models.AccessError{Code:"", Message:"Method Not Allowed", Detail:""}
[2019/09/11 11:49:34 UTC] [EROR] (jfrog.com/xray/internal/handlers/auth.AuthHandler.SsoExchange:343) statusCode: 405,
 models.AccessError{Code:"", Message:"Method Not Allowed", Detail:""}
`
I looked at this page: https://jfrog.com/knowledge-base/why-does-my-login-to-xray-ui-fail-with-a-message-error-token-exchange-in-the-browser-after-entering-credentials-during-the-sso-redirect/
but I don't get a 401 error, plus this setup worked just fine before I updated.

**Comment by eldada** [comment]
Can you share the commands used to apply the upgrade?

**Comment by asafambar** [comment]
What was changed in the setup? 
One option can be a reverse proxy that translated the Method to the request between Xray<>Artifactory.
e.g
POST translated to GET

Please provide more information on the installation.

**Comment by SnorreSelmer** [comment]
I installed the Artifactory and XRay stacks as per the instructions on this site, on CentOS 7. All required folders were created with the right permissions.

artifactory-pro: 6.12.1
xray: 2.8.9

I'm unable to use git on the server in question, so all scripts were copy-pasted in. Also, two modifications were made to the docker-compose file:
- First I removed the exposing of PostgreSQL to the host. Nothing external should need to access PostgreSQL, so I saw no need to expose it.
- Second, the XRAY_SERVER_PORT variable in the .env file caused us issues when we tried running the service on a custom port, because the compose-file changes both the internal and external ports for xray-server, but doesn't tell the xray service to also listen to the port inside the image. this means that in the compose-file xray-server section I have the following:
`    ports:
      - "$XRAY_SERVER_PORT:8000"`

The stacks were then fired up, and our Apache reverse-proxy was configured as per JFrog's instuctions, I logged in as admin on both instances, triggered the vulnerability-database download on xray and everything worked great.

Then yesterday I saw that there are new versions of both xray and artifactory, so I started with xray, went into the .env-file, changed the XRAY_VERSION variable from 2.8.9 to 2.9.0 and did a
`docker-compose -f xray-compose.yml up -d`.
The process, pulls the new images and starts the updated xray service. I go to the URL to verify a successful upgrade, get the login-page, log in, and BAM! 405 error in the log, no login.

**Comment by SnorreSelmer** [comment]
`20190913064224|55|REQUEST|[my IP]|anonymous|POST|/ui/auth/login|HTTP/1.1|200|60
20190913064224|25|REQUEST|[my IP]|admin|GET|/ui/auth/redirect|HTTP/1.1|200|0
20190913064224|1|REQUEST|[internet proxy server address]|non_authenticated_user|GET|/api/system/gateway/openid/token|HTTP/1.1|405|0
`
Frustrating and a bit embarrassing, but the problem has been found and resolved.

When we set up the reverse-proxy, we did a bit of testing, and things were commented out in the proxy-config. Now that the service is up and running, one of our people cleaned out the unused (commented) code, and managed to remove the header-rewrite in the process.

So I apologize for wasting your time on a non-issue. I'm taking this as a reminder to not assume that the upstream (reverse-proxy in this case) is fine, and revise my upgrading-procedure to include some more pre-upgrade checking. But the timing of this couldn't have been worse, the reverse-proxy cleanup was done at the same time as I was upgrading, so it looked like the upgrade was the culprit. Oh well.. ;)

Thanks for great help in locating the issue

**Comment by eldada** [comment]
Happy it's resolved @SnorreSelmer !
We are always happy to help.

**Comment by rbjorklin** [comment]
@SnorreSelmer could you provide some more details on your header rewrites? We're seeing a very similar issue and we're currently suspecting our reverse-proxy as well. We're using Haproxy so if you are too any suggestions would be greatly appreciated!

**Comment by SnorreSelmer** [comment]
Not using HAProxy, just a standard Apache reverse proxy. The header-rewrites we used were the same as are recommended in the JFrog documentation.
