### ISSUE TITLE
Helm deployment failure on IBM kubernetes cluster using persistence volume

### ISSUE THREAD

**Issue by akashpatel567** [jfrog/artifactory-docker-examples#181]
Hello,

I am using 8.2.4 version from https://charts.jfrog.io/ but not able to make it work when persistence volume is true.

It works when persistence volume is false. 

Note: Everytime I have cleaned the release and remove the pvc before the redeployment. Matched the password in artifactory and postgres container is same. Hardcoded the password but error remains same. 
Please let me know what could be possible solution to it.

**Error:**
 Role "artifactory" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
] FATAL:  password authentication failed for user "artifactory"
DETAIL:  Role "artifactory" does not exist.

Thank You

**Comment by eldada** [comment]
I see you also opened this in https://github.com/jfrog/charts/issues/598. We'll work on it there. Closing here.
