### ISSUE TITLE
No Wizard after bootstrap

### ISSUE THREAD

**Issue by R-Rudolf** [jfrog/artifactory-docker-examples#183]
After first starting the oss docker compose example, after logging in with access-admin the wizard does not appear, to set new admin password.
It worked for me in version 6.14.1, but not in 6.16, nor 6.17.

**Comment by eldada** [comment]
@R-Rudolf - is this a fresh new install (not using old exiting volumes)?

**Comment by asinvrer** [comment]
Cuz

**Comment by R-Rudolf** [comment]
I changed the version in the existing docker compose file, but executed a compose down with the extra -v volume removal flag.

Until then as a workaround I used the password recovery process:
```
docker exec -ti artifactory bash
echo "access-admin@*=tempPassword" > $ARTIFACTORY_HOME/access/etc/bootstrap.creds
chmod 600 bootstrap.creds
exit
docker stop artifactory
docker start artifactory
 curl -uaccess-admin:tempPassword -XPATCH localhost:80/artifactory/api/access/api/v1/users/admin -H "Content-Type: application/json" -d '{"password":"new-password"}'
```

**Comment by JfrogPrasanna** [comment]
There is a new wizard in the 7.x version to  onboard Artifactory and all other  extensions in the   JPD.  Going ahead and closing this as this repo is under deprecation.
