### ISSUE TITLE
Artifactory failed to initialize (failed fetching external topology)

### ISSUE THREAD

**Issue by walterjgsp** [jfrog/artifactory-docker-examples#190]
I'm trying to initialize the artifactory and using the latest image on docker I'm not being able to start the application. And getting the following error before the container stop:

```bash
2020-03-02T17:53:53.429Z [jfrt ] [INFO ] [36e4d89fc1215e2d] [ctoryContextConfigListener:250] [art-init            ] - Artifactory (jfrt) service initialization completed in 57.267 seconds. Listening on port: 8081
2020/03/02 17:53:58 httputil: ReverseProxy read error during body copy: unexpected EOF
2020-03-02T17:53:58.262Z [jfmd ] [ERROR] [                ] [compatibility_logger.go:28    ] [main                ] - Refreshing affected permissions stream - got an error (status: [Internal]) [access_client]
/opt/jfrog/artifactory/app/bin/artifactory.sh: line 576:  2466 Killed                  $TOMCAT_HOME/bin/catalina.sh run > >(tee >(redirectServiceLogsToFile)) 2>&1
2020-03-02T17:53:58.319Z [jfrou] [ERROR] [1d04da05e2d80891] [external_topology.go:85       ] [main                ] - failed fetching external topology from Access: Get http://localhost:8040/access/api/v1/topology: dial tcp 127.0.0.1:8040: connect: connection refused
```

I followed all the steps on the documentation, the only thing I changed was the command:

```bash
chown -R 1030:1030 $JFROG_HOME/artifactory/var
```

I discovered my UserID and GroupID and replaced the values. I need ideas on how to fix this problem and make the application run using docker.

Thanks for the help guys.

**Comment by JfrogPrasanna** [comment]
Are you running your container also as your UserID and GroupID? (by  passing --user 1000:1000)
I suspect some permission issue on the var folder.
Can you relook at other errors in the console.log and tomcat logs and see if there are any permission issues thrown?

Thanks 
Prasanna

**Comment by JfrogPrasanna** [comment]
Also pls note this repo is deprecated and the new  compose is formally supported here: 
compose: https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation
helm: https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-HelmInstallation

**Comment by walterjgsp** [comment]
Something really weird happened. To not use a lot of resources I stopped my Sonarqube container and tried to run Artifactory again, and it works. But when I started the Sonarqube container the Artifactory container just stopped. So right now I can run one or another, but Artifactory worked.

**Comment by walterjgsp** [comment]
The problem was a lack of resources. After I alter the docker setup on my machine letting it use more memory for the containers both frameworks worked simultaneously. 

Thanks for the help!
