### ISSUE TITLE
Setting up artifactory-oss Master key problem

### ISSUE THREAD

**Issue by Haso58** [jfrog/artifactory-docker-examples#195]
Hi,

I am pretty new to docker. So I wanted to try to use artifactory with docker. after I start up artifactory-oss-postgress.yml the image starts. But in the Logs it shows me this error 

`Failed resolving master key: failed resolving 'shared.security.masterKey' key; file does not exist: /opt/jfrog/artifactory/var/etc/security/master.key`

and when I try to use the prepareHostEnvironment.sh I am getting this error.

`Are you sure you want to remove existing /data [y/n]: y
Removing old /data
Creating /data
First setup. Setting FIRST_SETUP=true
Copying needed files to directories
Artifactory configuration files
cp: cannot stat './../../files/access': No such file or directory`

And because of that I can not open artifactory via my browser. Can someone maybe help me out with this problem? My System is Ubuntu

**Comment by eldada** [comment]
Hi @Haso58 . This repository is deprecated and not maintained anymore.
We have now an official Docker compose distribution you can download and use from the [official Artifactory OSS download page](https://jfrog.com/open-source/#artifactory).
