### ISSUE TITLE
Docker-compose for pro for version 7.x , where i can download ? 

### ISSUE THREAD

**Issue by raj333921** [jfrog/artifactory-docker-examples#202]
Please suggest us a URL for docker-compose 7z file

**Comment by MaciejKucia** [comment]
You can get compose at https://jfrog.com/download-jfrog-platform/

Also https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation

**Comment by DPatrickBoyd** [comment]
there is no 7z file, but it took me a little bit to figure out that you can download the tar.gz from the download link, its the first picture with the octopus holding the containers.
