### ISSUE TITLE
master key not found while starting with default derby database

### ISSUE THREAD

**Issue by sooraj2589** [jfrog/artifactory-docker-examples#204]
Getting error master key not found while starting with default derby database. Used the same artifactory-oss.yml file

artifactory    | 2020-10-04 07:05:51,731 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:05:53,736 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:05:55,737 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:05:57,739 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:05:59,741 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:06:01,742 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...
artifactory    | 2020-10-04 07:06:03,744 [localhost-startStop-2] [JFrog-Access] [WARN ] (o.j.s.c.KeyUtils    :66) - master.key not found, waiting for sync...

Could anyone please advise?

**Comment by eldada** [comment]
@sooraj2589 - this repository is deprecated and is no longer being maintaned.
1. Download the [Artifactory Docker Compose](https://jfrog.com/open-source/).
2. Follow the latest Docker Compose installation instructions from the [official JFrog Artifactory install](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation)
