### ISSUE TITLE
is this repo works for artifcatory,postgres and file store to create with docker compose?

### ISSUE THREAD

**Issue by sooraj2589** [jfrog/artifactory-docker-examples#206]

**Comment by eldada** [comment]
This repository is deprecated.
1. Download artifactory from the [official Artifactory download page](https://jfrog.com/download-jfrog-platform/).
2. Follow [Docker compose](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation) installation guide.
