### ISSUE TITLE
HA setup is not working

### ISSUE THREAD

**Issue by sooraj2589** [jfrog/artifactory-docker-examples#207]
Tried out the HA setup in the repo But the artifactory, nginx containers not starting

Is the repo yaml files depreciated? could anyone redirect me to right repo path for ha setup?

**Comment by eldada** [comment]
This repository is deprecated.

I assume you mean Docker compose...

1. Download artifactory from the [official Artifactory download page](https://jfrog.com/download-jfrog-platform/).
2. Follow [Docker compose](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation.1) HA installation guide.
