### ISSUE TITLE
Run Artifactory as Docker container response 404

### ISSUE THREAD

**Issue by hannesa2** [jfrog/artifactory-docker-examples#214]
It's copy of https://stackoverflow.com/a/70531262/1079990
I start my instance with

    sudo groupadd -g 1030 artifactory
    sudo useradd -u 1030 -g artifactory artifactory
    sudo chown artifactory:artifactory /daten/jfrog -R
    
    docker run \
    -d \
    --name artifactory \
    -v /daten/jfrog/artifactory:/var/opt/jfrog/artifactory \
    --user "$(id -u artifactory):$(id -g artifactory)" \
    --restart always \
    -p 8084:8081 -p 9082:8082 releases-docker.jfrog.io/jfrog/artifactory-oss:latest

This is my `/daten/jfrog/artifactory/etc/system.yaml` (I changed nothing manually)

    ## @formatter:off
    ## JFROG ARTIFACTORY SYSTEM CONFIGURATION FILE
    ## HOW TO USE: comment-out any field and keep the correct yaml indentation by deleting only the leading '#' character.
    configVersion: 1
    ## NOTE: JFROG_HOME is a place holder for the JFrog root directory containing the deployed product, the home directory for all JFrog products.
    ## Replace JFROG_HOME with the real path! For example, in RPM install, JFROG_HOME=/opt/jfrog
    
    ## NOTE: Sensitive information such as passwords and join key are encrypted on first read.
    ## NOTE: The provided commented key and value is the default.
    
    ## SHARED CONFIGURATIONS
    ## A shared section for keys across all services in this config
    shared:
        ## Java 11 distribution to use
        #javaHome: "JFROG_HOME/artifactory/app/third-party/java"
    
        ## Extra Java options to pass to the JVM. These values add to or override the defaults.
        #extraJavaOpts: "-Xms512m -Xmx2g"
    
        ## Security Configuration
        security:
        ## Join key value for joining the cluster (takes precedence over 'joinKeyFile')
        #joinKey: "<Your joinKey>"
    
        ## Join key file location
        #joinKeyFile: "<For example: JFROG_HOME/artifactory/var/etc/security/join.key>"
    
        ## Master key file location
        ## Generated by the product on first startup if not provided
        #masterKeyFile: "<For example: JFROG_HOME/artifactory/var/etc/security/master.key>"
    
        ## Maximum time to wait for key files (master.key and join.key)
        #bootstrapKeysReadTimeoutSecs: 120
    
        ## Node Settings
        node:
        ## A unique id to identify this node.
        ## Default auto generated at startup.
        #id: "art1"
    
        ## Default auto resolved by startup script
        #ip:
    
        ## Sets this node as primary in HA installation
        #primary: true
    
        ## Sets this node as part of HA installation
        #haEnabled: true
    
        ## Database Configuration
        database:
    
    ## One of mysql, oracle, mssql, postgresql, mariadb
    ## Default Embedded derby
    
    ## Example for postgresql
    #type: postgresql
    #driver: org.postgresql.Driver
    #url: "jdbc:postgresql://<your db url, for example: localhost:5432>/artifactory"
    #username: artifactory
    #password: password

[![enter image description here][1]][1]

I see this in `router-request.log`

    {"BackendAddr":"localhost:8040","ClientAddr":"127.0.0.1:43740","DownstreamContentSize":95,"DownstreamStatus":404,"Duration":3608608,"RequestMethod":"GET","RequestPath":"/access/api/v1/users/jffe@000?expand=groups","StartUTC":"2021-12-30T11:49:19.56803042Z","level":"info","msg":"","request_Uber-Trace-Id":"664d23ea1941d9b0:410817c2c69f2849:31b50a1adccb9846:0","request_User-Agent":"JFrog Access Java Client/7.29.9 72909900  Artifactory/7.29.8 72908900","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8040","ClientAddr":"127.0.0.1:43734","DownstreamContentSize":95,"DownstreamStatus":404,"Duration":4000683,"RequestMethod":"GET","RequestPath":"/access/api/v1/users/jffe@000?expand=groups","StartUTC":"2021-12-30T11:49:19.567751867Z","level":"info","msg":"","request_Uber-Trace-Id":"23967a8743252dd8:436e2a5407b66e64:31cfc496ccc260fa:0","request_User-Agent":"JFrog Access Java Client/7.29.9 72909900  Artifactory/7.29.8 72908900","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8040","ClientAddr":"127.0.0.1:43736","DownstreamContentSize":95,"DownstreamStatus":404,"Duration":4021195,"RequestMethod":"GET","RequestPath":"/access/api/v1/users/jffe@000?expand=groups","StartUTC":"2021-12-30T11:49:19.567751873Z","level":"info","msg":"","request_Uber-Trace-Id":"28300761ec7b6cd5:36588fa084ee7105:10fbdaadbc39b21e:0","request_User-Agent":"JFrog Access Java Client/7.29.9 72909900  Artifactory/7.29.8 72908900","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8040","ClientAddr":"127.0.0.1:43622","DownstreamContentSize":95,"DownstreamStatus":404,"Duration":3918873,"RequestMethod":"GET","RequestPath":"/access/api/v1/users/jffe@000?expand=groups","StartUTC":"2021-12-30T11:49:19.567751891Z","level":"info","msg":"","request_Uber-Trace-Id":"6d57920d087f4d0f:26b9120411520de2:49b0e61895e17734:0","request_User-Agent":"JFrog Access Java Client/7.29.9 72909900  Artifactory/7.29.8 72908900","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8040","ClientAddr":"127.0.0.1:43742","DownstreamContentSize":95,"DownstreamStatus":404,"Duration":2552815,"RequestMethod":"GET","RequestPath":"/access/api/v1/users/jffe@000?expand=groups","StartUTC":"2021-12-30T11:49:19.569112324Z","level":"info","msg":"","request_Uber-Trace-Id":"d4a7bb216cf31eb:5c783ae80b95778f:fd11882b03eb63f:0","request_User-Agent":"JFrog Access Java Client/7.29.9 72909900  Artifactory/7.29.8 72908900","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8081","ClientAddr":"127.0.0.1:43730","DownstreamContentSize":45,"DownstreamStatus":200,"Duration":18106757,"RequestMethod":"POST","RequestPath":"/artifactory/api/auth/loginRelatedData","StartUTC":"2021-12-30T11:49:19.557661286Z","level":"info","msg":"","request_Uber-Trace-Id":"d4a7bb216cf31eb:640bf3bca741e43b:28f0abcfc40f203:0","request_User-Agent":"JFrog-Frontend/1.29.6","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8081","ClientAddr":"127.0.0.1:43726","DownstreamContentSize":169,"DownstreamStatus":200,"Duration":19111069,"RequestMethod":"GET","RequestPath":"/artifactory/api/crowd","StartUTC":"2021-12-30T11:49:19.557426794Z","level":"info","msg":"","request_Uber-Trace-Id":"664d23ea1941d9b0:417647e0e0fd0911:55e80b7f7ab0724e:0","request_User-Agent":"JFrog-Frontend/1.29.6","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8081","ClientAddr":"127.0.0.1:43724","DownstreamContentSize":496,"DownstreamStatus":200,"Duration":19308753,"RequestMethod":"GET","RequestPath":"/artifactory/api/securityconfig","StartUTC":"2021-12-30T11:49:19.557346739Z","level":"info","msg":"","request_Uber-Trace-Id":"6d57920d087f4d0f:7bdba564c07f8bc5:71b1b99e1e406d5f:0","request_User-Agent":"JFrog-Frontend/1.29.6","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8081","ClientAddr":"127.0.0.1:43728","DownstreamContentSize":2,"DownstreamStatus":200,"Duration":19140699,"RequestMethod":"GET","RequestPath":"/artifactory/api/saml/config","StartUTC":"2021-12-30T11:49:19.557516365Z","level":"info","msg":"","request_Uber-Trace-Id":"23967a8743252dd8:2f9035e56dd9f0c5:4315ec00a6b32eb4:0","request_User-Agent":"JFrog-Frontend/1.29.6","time":"2021-12-30T11:49:19Z"}
    {"BackendAddr":"localhost:8081","ClientAddr":"127.0.0.1:43732","DownstreamContentSize":148,"DownstreamStatus":200,"Duration":18907203,"RequestMethod":"GET","RequestPath":"/artifactory/api/httpsso","StartUTC":"2021-12-30T11:49:19.557786692Z","level":"info","msg":"","request_Uber-Trace-Id":"28300761ec7b6cd5:2767cf480f6ebd73:2c013715cb58b384:0","request_User-Agent":"JFrog-Frontend/1.29.6","time":"2021-12-30T11:49:19Z"}

I've to change the port to 8084 (it's already occupied) But I run into 404 as well.

Who knows how to solve it ?

  [1]: https://i.stack.imgur.com/mTVK0.png

**Comment by eldada** [comment]
I answered on StackOverflow.:
> You are forwarding 8084 to artifactory port (8081) that does not have the /ui context. You should open https://latitude:9082/ui to get the UI.

Let's continue there. This repository us deprecated.
