### ISSUE TITLE
Helm installer post deploy message does  not apply to AWS

### ISSUE THREAD

**Issue by shrajfr12** [jfrog/artifactory-docker-examples#62]
After successfully deploying to kurbernetes via helm on AWS, the following message is deployed.
===
Congratulations. You have just deployed JFrog Artifactory Pro!
1. Get the Artifactory URL by running these commands:

   NOTE: It may take a few minutes for the LoadBalancer IP to be available.
         You can watch the status of the service by running 'kubectl get svc -w nginx'
   export SERVICE_IP=$(kubectl get svc --namespace default nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
   echo http://$SERVICE_IP/
..
=====

On AWS, kubectl get svc outputs a hostname instead of IP address, SERVICE_IP evauates to empty string. Replacing ingress[0].ip with ingress[0]hostname works fine in AWS.  So the message displayed is pertinent to GCP only and not to AWS. Either the message can be made cloud aware  or can be made more generic

**Comment by eldada** [comment]
@shrajfr12 - Can you open this in our [official helm charts repository](https://github.com/jfrog/charts)? The charts are not here anymore...
