### ISSUE TITLE
Documentation - How to install plugins in Artifactory if helm charts are used?

### ISSUE THREAD

**Issue by ankushchadha** [jfrog/artifactory-docker-examples#70]
If Artifactory is installed via Helm Charts, there is no easy way to install plugins. Like the use of ConfigMaps as documented here - https://github.com/JFrogDev/artifactory-docker-examples/tree/master/openshift/artifactory#installing-user-plugins

**Comment by eldada** [comment]
@ankushchadha - can you open this in https://github.com/jfrog/charts ?
