### ISSUE TITLE
Make server_name Configurable in Artifactory charts.

### ISSUE THREAD

**Issue by jainishshah17** [jfrog/artifactory-docker-examples#71]
When we deploy Artifactory using charts it takes artifactory service name as Server Name. To change it to domain name we need to manually exec into pod and change it. IF container crashes it reverts nginx configuration to default.

**Comment by jainishshah17** [comment]
@ankushchadha @eldada

**Comment by ryancurrah** [comment]
Why was this closed?

**Comment by jainishshah17** [comment]
@ryancurrah You can make this changes in Artifactory -> Admin -> Configuration -> HTTP Settings. Once you save this changes in Artifactory it will be applied to Nginx automatically.

**Comment by ryancurrah** [comment]
Ok thanks!
