### ISSUE TITLE
Error when using ha-shared-data

### ISSUE THREAD

**Issue by cyrilc-pro** [jfrog/artifactory-docker-examples#74]
Running `prepareHostEnv.sh` for `ha-shared-data` gives an error.

```
./prepareHostEnv.sh -t ha-shared-data -c
On Mac. Setting DEFAULT_ROOT_DATA_DIR to /Users/cyrilchene/.artifactory
Creating /Users/cyrilchene/.artifactory
Copying needed files to directories
Artifactory configuration files
Nginx Artifactory configuration
cp: ./../files/nginx/conf.d/ha-shared-data/*: No such file or directory
```

**Comment by nimerb** [comment]
@cyrilc-pro Thank you for the heads up, on it.

**Comment by nimerb** [comment]
@cyrilc-pro We have committed a change to fix this.

**Comment by eldada** [comment]
@cyrilc-pro - can you confirm the fix is good?

**Comment by cyrilc-pro** [comment]
@eldada Sorry, I can't right now. I'll let you know if/when I can...

**Comment by nimerb** [comment]
@cyrilc-pro can you please update if the fix was sufficient ?

**Comment by cyrilc-pro** [comment]
Yes, it works, but it looks like load balancer does not work correctly.

I had to manually execute the following steps:
* Copy master.key from node1 to node2
* Restart (I'm not sure this is required)
* Log into node1 (port 8081) and add two valid licenses.
* Restart (I'm not sure this is required)

Without those steps, I had 50% of HTTP requests sent to nginx fail with 404 Not Found.

**Comment by nimerb** [comment]
@cyrilc-pro Thank you for the update, we will check this issue.

**Comment by eldada** [comment]
@cyrilc-pro - are you open to using helm? 
We have our latest `artifactory-ha` helm chart in https://github.com/kubernetes/charts/tree/master/stable/artifactory-ha. You can install a fully functional **Artifactory HA** with support for several storage options.

**Comment by cyrilc-pro** [comment]
@eldada I'll think about it next time I need to install an Artifactory cluster.

**Comment by eldada** [comment]
@cyrilc-pro - I suggest you don't wait too long ;-) 
Try it out. Get comfortable with our helm charts. They are the recommended way to deploy Artifactory and Artifactory HA to K8s.

**Comment by esn89** [comment]
I'm having the same problem here, that dir is not fou nd.

**Comment by esn89** [comment]
can this please be pulled asap

**Comment by eldada** [comment]
@esn89 - This should be fixed with the same fix used in https://github.com/jfrog/artifactory-docker-examples/issues/95. Can you confirm?

**Comment by esn89** [comment]
It works, thank you!
