### ISSUE TITLE
Postgress, Artifactory, and Nginx all don't have write permission

### ISSUE THREAD

**Issue by wcott** [jfrog/artifactory-docker-examples#75]
Following the documentation here to get a docker private registry deployed on containers: https://www.jfrog.com/confluence/display/RTF/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-UsingDockerCompose-1MinuteSetup.1

After running this command:
`curl -L 'https://bintray.com/api/v1/content/jfrog/run/art-compose/$latest/art-compose?bt_package=art-compose' | sudo bash`

All of my containers are restarting with the following errors:

Postgresql
> chmod: changing permissions of ‘/var/lib/postgresql/data’: Permission denied

Artifactory
> mkdir: cannot create directory ‘/var/opt/jfrog/artifactory/data’: Permission denied

Nginx
> mkdir: cannot create directory '/var/opt/jfrog/nginx/conf.d': Permission denied

All of these directories are the specified volumes in the compose file.

**Comment by eldada** [comment]
Hi @wcott . We need some more information for this.
- What OS are you running on?
- Is this your first attempt?
- This `art-compose` script create these directories on the host. Were these already create before?

Can you paste the output of the whole process?

**Comment by wcott** [comment]
I discovered the issue. The issue was with SELinux on CentOS. You resolve it by changing the volumes line from:

`/data/postgresql:/var/lib/postgresql/data`
to
`/data/postgresql:/var/lib/postgresql/data:z`

**Comment by nimerb** [comment]
@wcott Thank you for the update. We will try if the mentioned fix works well with different configurations. Your feedback is appreciated.

**Comment by williamhuangh** [comment]
@nimerb @eldada this looks similar to https://github.com/jfrog/artifactory-docker-examples/issues/72, we're running fedora

**Comment by nimerb** [comment]
@williamhuangh Thank you for your input we have committed a fix pending approval

**Comment by williamhuangh** [comment]
@nimerb the `mkdir: cannot create directory ‘/var/opt/jfrog/artifactory/data’: Permission denied` is the same as https://github.com/jfrog/artifactory-docker-examples/issues/72 , but https://github.com/jfrog/artifactory-docker-examples/issues/72 is for kubernetes, do you know what the equivalent fix in those yaml files may be?

**Comment by jainishshah17** [comment]
@williamhuangh  Can you try changing the owner of VolumeMount `/var/opt/jfrog/artifactory/` like `chown -R 1030:1030 /var/opt/jfrog/artifactory/`?

**Comment by williamhuangh** [comment]
@jainishshah17 nope, i still get the same error

**Comment by mtdeguzis** [comment]
See also #72

**Comment by mtdeguzis** [comment]
I just added the volume mode/label on the end of my service volume:

```
  - some_volume:/path:z
```

Bear in mind that z and Z are different. Consult selinux docs.

**Comment by Flash1212** [comment]
@mtdeguzis I know this is an old post, but where did you specify that label? Was it in the yml file or somewhere else?

**Comment by eldada** [comment]
@mtdeguzis - is this still relevant?

**Comment by mtdeguzis** [comment]
@eldada not sure what you are asking for, SELinux is always relevant :) As I am not the original reporter of this issue, I wouldn't be of more help than presenting test results from a RHEL-based system.

**Comment by eldada** [comment]
Opps - sorry @mtdeguzis . I meant to ask @wcott . 
@wcott - is this still relevant?

**Comment by ducttapecoder-vt** [comment]
@eldada Absolutely. I just ran into this issue and it's not documented at all with the instructions. I had to add :z for the artifactory and nginx mounts to get the container to start successfully.

**Comment by eldada** [comment]
Anyone up to submitting a pull request 😄?

**Comment by yiwu1** [comment]
I meet same issue here:
2019-12-02 09:05:02   [12 entrypoint-nginx.sh] To view the Dockerfile: 'cat /docker/nginx-artifactory-pro/Dockerfile.nginx'.
2019-12-02 09:05:02   [68 entrypoint-nginx.sh] Setting up directories if missing
mkdir: cannot create directory '/var/opt/jfrog/nginx/conf.d': Permission denied
2019-12-02 09:05:02   [38 38 functions.sh] ERROR: Failed creating /var/opt/jfrog/nginx/conf.d

If start other container with same storage,  I can see the directory has following permission, is it correct with uid 1030? or other permission needed?
root@nginx-657894485d-zw8hj:/var/opt/jfrog/nginx# ls -ld .
drwxrwsr-x 2 root 1030 4096 Dec  2 08:59 .

**Comment by yiwu1** [comment]
Finally chown 104:107 to resolved the permission issue.

**Comment by mtdeguzis** [comment]
I would think if `getenforce` is "Enforcing" and SELinux is on, you default to a sane label.

**Comment by JfrogPrasanna** [comment]
Closing the issue due  to inactivity.
