### ISSUE TITLE
How to best bootstrap a container based on jFrog image?

### ISSUE THREAD

**Issue by praqmaTim** [jfrog/artifactory-docker-examples#85]
I was wondering how I bootstrap from Jfrogs base image. I would like to have pre-configured LDAP settings, DB connection, repositories and structure.

Would it be sufficient to copy own files , artifactory.config.xml, artifactory.system.properties, db.properties to images artifactory home?
e.g. something like:
```
ENV ARTIFACTORY_HOME=/opt/jfrog/artifactory

COPY ./etc ${ARTIFACTORY_HOME}/etc
```

**Comment by jainishshah17** [comment]
@praqmaTim We do have the simple option available to bootstrap Artifactory with configurations.
Mount directory putting all configuration file in it to `/artifactory_extra_conf/`. 
e.g 
```
## Create directory to store configuration. (We are going to mount this directory with `/artifactory_extra_conf/` of container)
mkdir -p artifcatory_config
## Copy configuration files to created  directory
cp artifactory.config.import.xml artifcatory_config/artifactory.config.import.xml
cp security.import.xml  artifcatory_config/security.import.xml
## Passing license is very important
cp artifactory.lic  artifcatory_config/artifactory.lic
## Run Artifactory container mounting this directory volume
docker run -d -p 8081:8081  -v ./artifcatory_config:/artifactory_extra_conf docker.bintray.io/jfrog/artifactory-pro:6.0.0
```

**Comment by praqmaTim** [comment]
Great! But what is the difference between artifactory.config.import.xml and artifactory.config.bootstrap.xml? I thought the configuration file was to be called bootstrap.

**Comment by jainishshah17** [comment]
@praqmaTim  `artifactory.config.bootstrap.xml` is for https://www.jfrog.com/confluence/display/RTF/Configuration+Files#ConfigurationFiles-BootstrappingtheGlobalConfiguration

**Comment by praqmaTim** [comment]
Thanks for the information!
