### ISSUE TITLE
"persistence.enabled=false" still mounts the PV

### ISSUE THREAD

**Issue by valdisrigdon** [jfrog/artifactory-docker-examples#91]
When running Artifactory HA using an RDS database and S3 storage, we would like to avoid having the local persistent disk. A number of things are cached there, such as database passwords, and subsequent restarts of the pods don't update values from `Secret`s.

**Comment by jainishshah17** [comment]
@valdisrigdon Can you provide more information. Are you using Helm charts or Kubernetes templates?

**Comment by valdisrigdon** [comment]
We are using the Helm charts.

**Comment by jainishshah17** [comment]
@valdisrigdon What is the version of helm chart?

**Comment by valdisrigdon** [comment]
0.2.0

**Comment by jainishshah17** [comment]
@valdisrigdon In that version, we do not have support for local storage. I recommend using the latest version of helm chart with the flag `artifactory.persistence.local=true` .

**Comment by jainishshah17** [comment]
@valdisrigdon Any update on this issue?

**Comment by valdisrigdon** [comment]
I'll close this. In the latest version of the helm chart, we can avoid using PVs.
