### ISSUE TITLE
Examples use links instead of networks

### ISSUE THREAD

**Issue by mtdeguzis** [jfrog/artifactory-docker-examples#93]
The links directive is legacy, and should not be used: https://docs.docker.com/network/links/. Is there a reason links are being used here? I am using a network with no issue (e.g. "artifactory-network")

>Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.
>
See Differences between user-defined bridges and the default bridge for some alternatives to using --link.

**Comment by eldada** [comment]
@mtdeguzis - thanks for the note. You are right!
These examples are old, so they still use links.
Do you want to submit a pull request with the suggested improvement?

**Comment by JfrogPrasanna** [comment]
Due to inactivity am closing this issue.

**Comment by mtdeguzis** [comment]
You closed the issue despite the example not being fixed? Huh? Of course individuals get busy, and while it would/would have been great to get a free PR from an end-user, it is still the responsibility of this repo to correct the example. This is especially true of a vendor-backed code repository.

**Comment by jfrog-aparicio** [comment]
@mtdeguzis These examples are deprecated and no longer being updated. We do have a new docker-compose that should not have this issue. It is now part of the official JFrog release (https://jfrog.com/download-jfrog-platform/), as opposed to just an example here in GitHub.

Give these a try and we would love to hear any feedback on making them better.

**Comment by mtdeguzis** [comment]
@jfrog-aparicio , due to some requirements, we run this on a VM now. This was from a "past life." Sorry that I can't confirm/contribute to this anymore. My last comment was only to highlight that the issue should still be resolve so folks in the future do not hit any issues. But, as noted, if they are deprecated and noted as so, no need to do anything.
