### ISSUE TITLE
Can't deploy helm charts onto Kubernetes cluster

### ISSUE THREAD

**Issue by mordf** [jfrog/artifactory-docker-examples#94]
Trying to deploy the helm charts according to the instructions in the README.md (https://github.com/jfrog/artifactory-docker-examples/tree/master/kubernetes/helm/artifactory)  and according to this post: https://jfrog.com/blog/confessions-of-a-devops-frog-automating-artifactory-deployment-to-kubernetes-is-actually-easy/

But i'm getting some errors on mounting volumes:
`Unable to mount volumes for pod "artifactory-postgresql-546887d8b9-v2rcr_default(01f63411-9305-11e8-b908-000d3ab658f8)": timeout expired waiting for volumes to attach/mount for pod "default"/"artifactory-postgresql-546887d8b9-v2rcr". list of unattached/unmounted volumes=[data]`

The cluster is located on Azure, am I supposed to create manually the PV and PVC before deploying the charts?

**Comment by eldada** [comment]
@mordf - can you try using the official chart from https://github.com/helm/charts/tree/master/stable/artifactory ?
We are in the process of updating our charts (still a few open PRs). Once done, we'll update here as well.

**Comment by mordf** [comment]
I used the official charts, since if I go through your this link:
https://jfrog.com/blog/confessions-of-a-devops-frog-automating-artifactory-deployment-to-kubernetes-is-actually-easy/

It takes the official charts, right?

**Comment by jainishshah17** [comment]
@mordf Yes, It takes the official charts. 
Can you share the output of `kubectl describe $STORAGE_CLASS/$PVC_NAME/$POD_NAME/`
also detail about your `kubectl` and `helm` version

**Comment by mordf** [comment]
```
helm version: 2.8.1
kubectl version: 1.9.5

```
`$STORAGE_CLASS/$PVC_NAME` don't exist (this is probably my problem) why any of them is being created?

`kubectl describe pod --namespace=artifactory gone-anteater-artifactory-5876966dfd-vv4lj`
Name:           gone-anteater-artifactory-5876966dfd-vv4lj
Namespace:      artifactory
Node:           -----
Start Time:     Wed, 01 Aug 2018 05:53:40 +0000
Labels:         app=artifactory
                component=artifactory
                pod-template-hash=1432522898
                release=gone-anteater
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/gone-anteater-artifactory-5876966dfd
Init Containers:
  remove-lost-found:
    Container ID:  
    Image:         alpine:3.6
    Image ID:      
    Port:          <none>
    Command:
      sh
      -c
      rm -rfv /var/opt/jfrog/artifactory/lost+found /var/opt/jfrog/artifactory/data/.lock
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
  wait-for-db:
    Container ID:  
    Image:         alpine:3.6
    Image ID:      
    Port:          <none>
    Command:
      sh
      -c
      until nc -z -w 2 gone-anteater-postgresql 5432 && echo database ok; do
  sleep 2;
done;

    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
Containers:
  artifactory:
    Container ID:   
    Image:          docker.bintray.io/jfrog/artifactory-pro:6.0.0
    Image ID:       
    Port:           8081/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8081/artifactory/webapp/%23/login delay=180s timeout=10s period=10s #success=1 #failure=10
    Readiness:      http-get http://:8081/artifactory/webapp/%23/login delay=60s timeout=10s period=10s #success=1 #failure=10
    Environment:
      DB_TYPE:             postgresql
      DB_USER:             artifactory
      DB_PASSWORD:         <set to the key 'postgres-password' in secret 'gone-anteater-postgresql'>  Optional: false
      DB_HOST:             gone-anteater-postgresql
      EXTRA_JAVA_OPTIONS:   
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  artifactory-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  gone-anteater-artifactory
    ReadOnly:   false
  default-token-9zn4v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9zn4v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age   From                                            Message
  ----     ------                 ----  ----                                            -------
  Normal   Scheduled              3m    default-scheduler                               Successfully assigned gone-anteater-artifactory-5876966dfd-vv4lj to ------
  Normal   SuccessfulMountVolume  3m    kubelet, ------  MountVolume.SetUp succeeded for volume "default-token-9zn4v"
  Warning  FailedMount            1m    kubelet, ------  Unable to mount volumes for pod "gone-anteater-artifactory-5876966dfd-vv4lj_artifactory(3dd8d3bc-954f-11e8-9bab-000d3ab15c33)": timeout expired waiting for volumes to attach/mount for pod "artifactory"/"gone-anteater-artifactory-5876966dfd-vv4lj". list of unattached/unmounted volumes=[artifactory-volume]`


`kubectl describe pod --namespace=artifactory gone-anteater-postgresql-8494cc89b5-fmvc4`
Name:           gone-anteater-postgresql-8494cc89b5-fmvc4
Namespace:      artifactory
Node:           -------
Start Time:     Wed, 01 Aug 2018 05:53:40 +0000
Labels:         app=gone-anteater-postgresql
                pod-template-hash=4050774561
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/gone-anteater-postgresql-8494cc89b5
Containers:
  gone-anteater-postgresql:
    Container ID:   
    Image:          postgres:9.6.2
    Image ID:       
    Port:           5432/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      100m
      memory:   256Mi
    Liveness:   exec [sh -c exec pg_isready --host $POD_IP] delay=60s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [sh -c exec pg_isready --host $POD_IP] delay=5s timeout=3s period=5s #success=1 #failure=3
    Environment:
      POSTGRES_USER:         artifactory
      PGUSER:                artifactory
      POSTGRES_DB:           artifactory
      POSTGRES_INITDB_ARGS:  
      PGDATA:                /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD:     <set to the key 'postgres-password' in secret 'gone-anteater-postgresql'>  Optional: false
      POD_IP:                 (v1:status.podIP)
    Mounts:
      /var/lib/postgresql/data/pgdata from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  gone-anteater-postgresql
    ReadOnly:   false
  default-token-9zn4v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9zn4v
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age              From                                            Message
  ----     ------                 ----             ----                                            -------
  Normal   Scheduled              6m               default-scheduler                               Successfully assigned gone-anteater-postgresql-8494cc89b5-fmvc4 to -----
  Normal   SuccessfulMountVolume  6m               kubelet, ------  MountVolume.SetUp succeeded for volume "default-token-9zn4v"
  Warning  FailedMount            2m (x2 over 4m)  kubelet, -----  Unable to mount volumes for pod "gone-anteater-postgresql-8494cc89b5-fmvc4_artifactory(3dd51aca-954f-11e8-9bab-000d3ab15c33)": timeout expired waiting for volumes to attach/mount for pod "artifactory"/"gone-anteater-postgresql-8494cc89b5-fmvc4". list of unattached/unmounted volumes=[data]

I also tried to pass persistence.enabled=false both for the nginx and Artifactory and it still didn't work.

**Comment by jainishshah17** [comment]
@mordf Exactly. Problem is K8s not being able to create PV and PVC dynamically.
You will have to create a storage class or you can create PVC manually and pass it to installation using values.yaml.

**Comment by mordf** [comment]
@jainishshah17 is that problem is a local problem I encounter or that is how K8S is work?

**Comment by mordf** [comment]
Thanks @jainishshah17 so I need to create 3 resources of PV and PVC? (Artifactory, Nginx, Postgresql)

**Comment by jainishshah17** [comment]
@mordf Yes, and pass them with `artifactory.persistence.existingClaim`, `postgresql.persistence.existingClaim` and `nginx.persistence.existingClaim`

**Comment by mordf** [comment]
`helm install --namespace=artifactory stable/artifactory --set artifactory.persistence.existingClaim=claim-artifactory --set nginx.persistence.existingClaim=claim-nginx --set postgresql.existingClaim=claim-postgresql`

claim-artifactory, claim-nginx and claim-postgresql are PVC's I created manually of course..

Like this I presume..
I'm still getting this error: 
Unable to mount volumes for pod "contrasting-moose-postgresql-7dcbf984df-swnb7_artifactory(05f7c8cf-99b2-11e8-90ba-000d3ab15c33)": timeout expired waiting for volumes to attach/mount for pod "artifactory"/"contrasting-moose-postgresql-7dcbf984df-swnb7". list of unattached/unmounted volumes=[data]
Also, the other pods aren't working as well.

Any idea @jainishshah17 ?

**Comment by jainishshah17** [comment]
You are missing `persistence` in `--set postgresql.existingClaim=claim-postgresql`

**Comment by mordf** [comment]
now i'm stuck on this situation:
NAME                                             READY     STATUS     RESTARTS   AGE
agile-saola-artifactory-df8f7b57d-w5649          0/1	   Init:1/2   0          3m
agile-saola-artifactory-nginx-7557d498cb-k6db4   0/1	   Init:0/1   0          3m
agile-saola-postgresql-796879746-ll4xg           1/1	   Running    0          3m

All mounts had succeeded but Artifactory and nginx refuse to start

**Comment by jainishshah17** [comment]
@mordf Can you provide the output of `kubectl describe pod POD_NAME` and logs of pods.

**Comment by mordf** [comment]
`kubectl describe pod --namespace=artifactory agile-saola-artifactory-df8f7b57d-w5649`

Name:           agile-saola-artifactory-df8f7b57d-w5649
Namespace:      artifactory
Node:           <VMDNS>/<IP>
Start Time:     Mon, 06 Aug 2018 20:42:03 +0000
Labels:         app=artifactory
                component=artifactory
                pod-template-hash=894936138
                release=agile-saola
Annotations:    <none>
Status:         Pending
IP:             <IP>
Controlled By:  ReplicaSet/agile-saola-artifactory-df8f7b57d
Init Containers:
  remove-lost-found:
    Container ID:  docker://3c6035fbfec284679b372fdb5806b8730117049bee357e21c2b8d6ee1eb7fd06
    Image:         alpine:3.6
    Image ID:      docker-pullable://alpine@sha256:de5701d6a3a36dc6a5db260d21be0422fd30dd2d158c1e048b34263e73205cb6
    Port:          <none>
    Command:
      sh
      -c
      rm -rfv /var/opt/jfrog/artifactory/lost+found /var/opt/jfrog/artifactory/data/.lock
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 06 Aug 2018 21:20:15 +0000
      Finished:     Mon, 06 Aug 2018 21:20:15 +0000
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
  wait-for-db:
    Container ID:  docker://edde79e5d84f405e35b7dbdd9a83457c5bf10a0e8377c260a5e2d10c9da6395c
    Image:         alpine:3.6
    Image ID:      docker-pullable://alpine@sha256:de5701d6a3a36dc6a5db260d21be0422fd30dd2d158c1e048b34263e73205cb6
    Port:          <none>
    Command:
      sh
      -c
      until nc -z -w 2 agile-saola-postgresql 5432 && echo database ok; do
  sleep 2;
done;

    State:          Running
      Started:      Mon, 06 Aug 2018 21:20:16 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
Containers:
  artifactory:
    Container ID:   
    Image:          docker.bintray.io/jfrog/artifactory-pro:6.0.0
    Image ID:       
    Port:           8081/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8081/artifactory/webapp/%23/login delay=180s timeout=10s period=10s #success=1 #failure=10
    Readiness:      http-get http://:8081/artifactory/webapp/%23/login delay=60s timeout=10s period=10s #success=1 #failure=10
    Environment:
      DB_TYPE:             postgresql
      DB_USER:             artifactory
      DB_PASSWORD:         <set to the key 'postgres-password' in secret 'agile-saola-postgresql'>  Optional: false
      DB_HOST:             agile-saola-postgresql
      EXTRA_JAVA_OPTIONS:   
    Mounts:
      /var/opt/jfrog/artifactory from artifactory-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9zn4v (ro)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  artifactory-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-artifactory
    ReadOnly:   false
  default-token-9zn4v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9zn4v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type    Reason                 Age   From                                            Message
  ----    ------                 ----  ----                                            -------
  Normal  Scheduled              40m   default-scheduler                               Successfully assigned agile-saola-artifactory-df8f7b57d-w5649 to
  Normal  SuccessfulMountVolume  40m   kubelet,                                        MountVolume.SetUp succeeded for volume "default-token-9zn4v"
  Normal  SuccessfulMountVolume  40m   kubelet,                                        MountVolume.SetUp succeeded for volume "nfs-artifactory"
  Normal  Pulled                 40m   kubelet,                                        Container image "alpine:3.6" already present on machine
  Normal  Created                40m   kubelet,                                        Created container
  Normal  Started                40m   kubelet,                                        Started container
  Normal  Pulled                 40m   kubelet,                                        Container image "alpine:3.6" already present on machine
  Normal  Created                40m   kubelet,                                        Created container
  Normal  Started                40m   kubelet,                                        Started container
  Normal  SuccessfulMountVolume  2m    kubelet,                                        MountVolume.SetUp succeeded for volume "default-token-9zn4v"
  Normal  SuccessfulMountVolume  2m    kubelet,                                        MountVolume.SetUp succeeded for volume "nfs-artifactory"
  Normal  SandboxChanged         2m    kubelet,   Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled                 2m    kubelet,   Container image "alpine:3.6" already present on machine
  Normal  Created                2m    kubelet,  Created container
  Normal  Started                2m    kubelet,   Started container
  Normal  Pulled                 2m    kubelet,   Container image "alpine:3.6" already present on machine
  Normal  Created                2m    kubelet,   Created container
  Normal  Started                2m    kubelet,   Started container

`kubectl logs --namespace=artifactory agile-saola-artifactory-df8f7b57d-w5649`
Error from server (BadRequest): container "artifactory" in pod "agile-saola-artifactory-df8f7b57d-w5649" is waiting to start: PodInitializing


`kubectl logs --namespace=artifactory agile-saola-artifactory-nginx-7557d498cb-k6db4`
Error from server (BadRequest): container "nginx" in pod "agile-saola-artifactory-nginx-7557d498cb-k6db4" is waiting to start: PodInitializing

**Comment by jainishshah17** [comment]
@mordf Can you verify is Postgres is up and running properly? looks like initContainer  2 of Artifactory pod which makes sure that  Postgres is up and running is getting stuck.

**Comment by mordf** [comment]
yep, looks like something wrong with the postgresql:
`FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied`

Any idea how to solve that?

**Comment by mordf** [comment]
I had deleted the pod and now it looks like the postgresql is working fine but i'm still suck on 
`Error from server (BadRequest): container "artifactory" in pod "agile-saola-artifactory-df8f7b57d-s4jqh" is waiting to start: PodInitializing`

**Comment by jainishshah17** [comment]
@mordf I recommend deleting this release using `helm delete --purge $RELEASE NAME`. Then clean all volumes then reinstall Artifactory.

**Comment by mordf** [comment]
I did that, now Postgresql pod looks just fine, but I still encounter the same problem with PodInitializing error..

`$ kubectl logs -f --namespace=artifactory inky-chicken-postgresql-577b645d96-8fd6s` 
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....LOG:  database system was shut down at 2018-08-07 06:17:29 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "artifactory" does not exist
 done
server started
CREATE DATABASE

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
waiting for server to shut down....LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-08-07 06:17:41 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

**Comment by mordf** [comment]
Also, when I type docker logs on the alpine image in the node where Artifactory POD resides I see this error:
`$ sudo docker logs d8853309b459`

nc: bad address 'inky-chicken-postgresql'
nc: bad address 'inky-chicken-postgresql'
nc: bad address 'inky-chicken-postgresql'
nc: bad address 'inky-chicken-postgresql'
nc: bad address 'inky-chicken-postgresql'

**Comment by jainishshah17** [comment]
@mordf can you provide output of `kubectl get svc` .

**Comment by mordf** [comment]
musty-puma-artifactory         ClusterIP      -----------   none        8081/TCP                     5m
musty-puma-artifactory-nginx   LoadBalancer   -------   pending     80:30744/TCP,443:31649/TCP   5m
musty-puma-postgresql          ClusterIP      --------   none        5432/TCP

**Comment by jainishshah17** [comment]
@mordf Can you send me the full error log. Also when you reinstalled Artifacotry did you clean PVs for Artifactory and Postgres? Also, can you change the permission of this 2 volumes to 777 and try installing Artifactory again?

**Comment by mordf** [comment]
@jainishshah17 I did clean the PV's and recreated them also changed the permissions to 777
I reinstalled Artifactory and again the only error I see when I `docker logs <alpineArtifactoryContainer>` is:
`nc: bad address 'sartorial-pig-postgresql'`

**Comment by jainishshah17** [comment]
@mordf Let's plan to have screen sharing session. I will able to help you more when I see real-time logs.

**Comment by mordf** [comment]
@jainishshah17 sounds excellent, tell me when

**Comment by jainishshah17** [comment]
@mordf I am available today 5-6 PM PST and 8:30-10 AM tomorrow. Let me know what time works for you.

**Comment by mordf** [comment]
8:30-10 tomorrow is better for me, thanks!

**Comment by jainishshah17** [comment]
@mordf PM me on Twitter https://twitter.com/jainishshah24. I will share zoom link for the meeting.

**Comment by mordf** [comment]
@jainishshah17 Can't PM you on twitter since you don't follow me
i'm @mfuxi1 on twitter

**Comment by mordf** [comment]
Finished the screen sharing session.
@jainishshah17 thanks a lot for your time!

The reason we are getting `nc: bad address` is because from some reason Artifactory doesn't know the artifactory-postgresql, we tried hacking the hosts file of the running container and adding to it and record of the artifactory-postgresql but it didn't help so we removed the `nc` command using `kubectl edit pod` command after that we got stuck on:
`[315 entrypoint-artifactory.sh] Waiting for DB postgresql to be ready on artifactory-postgresql/5432 within 30 seconds`

My Kubernetes cluster version is v1.9.5 (Deployed by Kubespray) and this could be a bug with this K8S version.

I'll upgrade my cluster to v1.9.6 and try to deploy Artifactory using HELM again.

**Comment by mordf** [comment]
@jainishshah17 I just would like to update that I upgraded my cluster to v1.9.6 and i'm still experiencing the same issue so apparently this has nothing to do with K8S version

**Comment by jainishshah17** [comment]
@mordf Can you check if your kubedns is working properly in your cluster?

**Comment by mordf** [comment]
@jainishshah17 `kubectl get pod -n kube-system` shows their status as running 3/3
But when i'm `kubectl logs -n kube-system kube-dns` I see this error:

**Error from server (BadRequest): a container name must be specified for pod kube-dns-79d99cdcd5-ggpml, choose one of: [kubedns dnsmasq sidecar]**

**Comment by mordf** [comment]
@jainishshah17 I would like to update that I just created a new cluster with KOPS on AWS and installed Artifactory on it with the HELM charts went smooth.

So apparently i'm missing some configuration with my kubespray deployment on Azure (probably something with networking)

Would you like me to close the issue?

**Comment by jainishshah17** [comment]
@mordf Thank you for updating me. I recommend to close this issue and open relevant one in kubespray.
