### ISSUE TITLE
The liveness probe in the mission control deployment is over indented and when passing a nodeselector 

### ISSUE THREAD

**Issue by Manojtuguru** [jfrog/artifactory-docker-examples#97]
Link to offending line of code: https://github.com/helm/charts/blob/edd5421c4724a1f41475b236bdf6d86b5de9e8a0/stable/mission-control/templates/mission-control-deployment.yaml#L117

**Comment by jainishshah17** [comment]
@Manojtuguru I have created PR with the fix. Here is link to PRhttps://github.com/helm/charts/pull/6449

**Comment by jainishshah17** [comment]
@Manojtuguru This PR is merged.
