### ISSUE TITLE
User Images are hard coded In the create-user.yaml

### ISSUE THREAD

**Issue by Manojtuguru** [jfrog/artifactory-docker-examples#98]
Ability to allow variables in images in the create-users.yaml:
 https://github.com/helm/charts/blob/edd5421c4724a1f41475b236bdf6d86b5de9e8a0/stable/mission-control/templates/hooks/create-user.yaml#L31

**Comment by jainishshah17** [comment]
@Manojtuguru I have created PR with the fix. Here is link to PRhttps://github.com/helm/charts/pull/6449

**Comment by jainishshah17** [comment]
@Manojtuguru PR is merged.
